### ISSUE TITLE
CUDA error: invalid device function

### ISSUE THREAD

**Issue by timurkakhanovich** [tk-rusch/LEM#1]
Hi there!
I faced with the problem where forward for the 'LEMcuda' layer not working (as a comparison I left the same code for the LSTM layer to make sure all works well).
I tried to set the 'CUDA_LAUNCH_BLOCKING' variable to 1 but it didn't help me.
![photo_2022-02-14_18-07-08](https://user-images.githubusercontent.com/78255426/153889738-b3da98a3-50fa-41d8-af52-6e8975efa26f.jpg)

**Comment by tk-rusch** [comment]
Hi, did you successfully compile the cuda extensions, i.e. in `LEM_cuda` directory do 
```python LEM_cuda_extension/setup.py install```
? 
If you do `pip list` afterwards, can you find something called `lem-cuda`?

Also: Can you reproduce the example I provide in the `LEM_cuda` directory, i.e. the FitzHughNagumo task explained there in the readme?

**Comment by timurkakhanovich** [comment]
Thank you for reply!
> Hi, did you successfully compile the cuda extensions, i.e. in `LEM_cuda` directory do `python LEM_cuda_extension/setup.py install` ? If you do `pip list` afterwards, can you find something called `lem-cuda`?

Yeah, the compilation has finished successfully and there is `lem-cuda` when calling `conda list` (if there is no difference between `pip` and `conda` when using lem_cuda all should work well)

> Also: Can you reproduce the example I provide in the `LEM_cuda` directory, i.e. the FitzHughNagumo task explained there in the readme?

Yes, I also tried to reproduce your example and I faced with the same problem.

Could there be a problem due to the difference between CUDA versions of the compiled project and mine (CUDA 10.2)?

**Comment by tk-rusch** [comment]
It indeed sounds like a version mismatch. You have to make sure that you compile the extensions with the same cuda version and c++ compiler you use for torch. If you use a very old torch version, this might also be a problem; for instance I tried it on two different machines using torch==1.9.0+cu102 and torch==1.7.1+cu101 (the first with cuda 10.2 and the seond with cuda 10.1) and it worked perfectly fine.

Another thing you can try is to use pytorch's just-in-time compiler (JIT), instead of compiling it before (this might not lead to a version mismatch). You can do this, by first uninstalling lem-cuda from conda (so that it doesn't use the old compiled version). Then copy everything from `LEM_cuda/LEM_cuda_extension` except for `setup.py` to `LEM_cuda/example`. After that, add the following lines at the very top of `LEM_cuda/example/network.py`:

```python
from torch.utils.cpp_extension import load
lem_cuda = load(name='lem_cuda', sources=['lem_cuda.cpp', 'lem_cuda_kernel.cu'])
```
and delete the import of `lem_cuda` in the same file.
After that, you can try to run the example, i.e. `python example/FitzHughNagumo_task.py`
Let me know, if this worked.

**Comment by timurkakhanovich** [comment]
Which version of GCC compiler did you use to build the extension?

**Comment by tk-rusch** [comment]
It worked fine for instance with gcc 6.3.0.
You can try if you can compile and run the following pytorch extension example: https://pytorch.org/tutorials/advanced/cpp_extension.html

Without a more precise error message it probably won't be fixed though.

**Comment by tk-rusch** [comment]
Closing for now because of inactivity. Feel free to open again.
